# Generated by Django 5.2.4 on 2025-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(default='GBP', max_length=3, verbose_name='Source Currency')),
                ('target_currency', models.CharField(default='EUR', max_length=3, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Rate')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'unique_together': {('source_currency', 'target_currency')},
            },
        ),
    ]
