# Generated by Django 5.2.4 on 2025-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GiBoard', max_length=100, verbose_name='Site Name')),
                ('contact_email', models.EmailField(blank=True, max_length=255, verbose_name='Public Contact Email')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If checked, a maintenance page will be shown to all non-staff users.', verbose_name='Maintenance Mode')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
