# Generated by Django 5.2.4 on 2025-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for this banner, e.g., 'Homepage Top Banner'", max_length=255, verbose_name='Banner Name')),
                ('image', models.ImageField(help_text='The actual banner image file.', upload_to='banners/%Y/%m/%d/', verbose_name='Image')),
                ('url', models.URLField(blank=True, help_text='The destination URL when the banner is clicked. Can be empty.', max_length=2000, null=True, verbose_name='URL Link')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the banner from the site without deleting it.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
