# Generated by Django 5.2.4 on 2025-08-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Field Name')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes / No')], max_length=10, verbose_name='Field Type')),
            ],
            options={
                'verbose_name': 'Field Definition',
                'verbose_name_plural': 'Field Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='categories.category')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='categories.field')),
            ],
            options={
                'verbose_name': 'Category Field',
                'verbose_name_plural': 'Category Fields',
                'unique_together': {('category', 'field')},
            },
        ),
    ]
