# Generated by Django 5.2.4 on 2025-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_field_categoryfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(help_text='A short, URL-friendly version of the name.', max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(help_text='A short, URL-friendly version of the name.', max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
