# Generated by Django 5.2.4 on 2025-08-11 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login Attempt'), ('logout', 'Logout'), ('pw_reset_request', 'Password Reset Request'), ('pw_reset_success', 'Password Reset Successful'), ('listing_created', 'Listing Created'), ('listing_deleted', 'Listing Deleted')], help_text='The type of action performed.', max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The IP address of the user when the action was performed.', null=True, verbose_name='IP Address')),
                ('details', models.TextField(blank=True, help_text='Any additional details about the action, e.g., user agent or object ID.', verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
