# Generated by Django 5.2.4 on 2025-08-11 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the specified currency', max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='GBP', help_text='Currency code (e.g., GBP, EUR)', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, help_text='The unique ID from the payment provider (e.g., Stripe, PayPal)', max_length=255, verbose_name='Gateway Transaction ID')),
                ('gateway_name', models.CharField(blank=True, help_text="e.g., 'Stripe', 'PayPal'", max_length=50, verbose_name='Gateway Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
