# Generated by Django 5.2.4 on 2025-08-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_es', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(help_text="A unique, URL-friendly version of the title. E.g., 'about-us'", unique=True, verbose_name='URL Slug')),
                ('content', models.TextField(blank=True, help_text='The main content of the page, can use HTML.', verbose_name='Content')),
                ('content_en', models.TextField(blank=True, help_text='The main content of the page, can use HTML.', null=True, verbose_name='Content')),
                ('content_es', models.TextField(blank=True, help_text='The main content of the page, can use HTML.', null=True, verbose_name='Content')),
                ('is_published', models.BooleanField(default=False, help_text='Check this to make the page visible on the site.', verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['title'],
            },
        ),
    ]
