# Generated by Django 5.2.4 on 2025-08-11 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR')], default='GBP', max_length=3, verbose_name='Currency')),
                ('sale_type', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('exchange', 'Exchange')], default='for_sale', max_length=10, verbose_name='Sale Type')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('na', 'Not Applicable')], default='used', max_length=10, verbose_name='Condition')),
                ('is_active', models.BooleanField(default=True, help_text='Is the listing visible to users?', verbose_name='Is Active')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='locations.city')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
