# Generated by Django 5.2.4 on 2025-08-11 10:08

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.get_listing_image_path, verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text='A short description of the image for accessibility and SEO.', max_length=255, verbose_name='Alt Text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images are displayed.', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['order'],
            },
        ),
    ]
