# Generated by Django 5.2.4 on 2025-08-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_field_categoryfield'),
        ('listings', '0002_listingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Value')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_values', to='categories.categoryfield')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Field Value',
                'verbose_name_plural': 'Listing Field Values',
                'unique_together': {('listing', 'field')},
            },
        ),
    ]
