# Generated by Django 5.2.4 on 2025-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
