# Generated by Django 5.2.4 on 2025-08-11 10:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_avatar_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_id',
            field=models.UUIDField(editable=False, help_text='A public identifier for the user, used in URLs and file paths.', null=True),
        ),
    ]
