# Generated by Django 5.2.4 on 2025-08-11 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A public identifier for the user, used in URLs and file paths.', unique=True),
        ),
    ]
