# Generated by Django 5.2.4 on 2025-08-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="User's explanation of why they are reporting this content.", verbose_name='Reason for Reporting')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved_valid', 'Resolved (Action Taken)'), ('resolved_invalid', 'Resolved (No Action Needed)')], default='submitted', max_length=20, verbose_name='Status')),
                ('moderator_notes', models.TextField(blank=True, help_text='Internal notes for the moderation team.', verbose_name='Moderator Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
