# Generated by Django 5.2.4 on 2025-08-11 15:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='A unique, URL-friendly version of the name.', unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text="Optional: Icon identifier, e.g., from Font Awesome like 'fa-utensils'.", max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Place Category',
                'verbose_name_plural': 'Place Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The precise point on the map. Click to set.', null=True, srid=4326, verbose_name='Geographic Location')),
                ('image', models.ImageField(blank=True, help_text='A featured image for the place.', null=True, upload_to='places/%Y/%m/%d/', verbose_name='Image')),
                ('is_approved', models.BooleanField(default=True, help_text='Uncheck this to hide the place from the main site.', verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.placecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
    ]
